[package]
name = "chia-sdk-driver"
version = "0.12.0"
edition = "2021"
license = "Apache-2.0"
description = "Driver code for interacting with standard puzzles on the Chia blockchain."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
chia-bls = { workspace = true }
chia-protocol = { workspace = true }
chia-puzzles = { workspace = true }
clvm-traits = { workspace = true }
clvm-utils = { workspace = true }
clvmr = { workspace = true }
thiserror = { workspace = true }
chia-sdk-types = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
hex = { workspace = true }

[dev-dependencies]
chia-sdk-test = { workspace = true }
anyhow = { workspace = true }
chia-consensus = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
tokio = { workspace = true, features = ["full"] }
