[package]
name = "chia-wallet-sdk"
version = "0.6.1"
edition = "2021"
license = "Apache-2.0"
description = "An unofficial SDK for building Chia wallets."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"

[dependencies]
tokio = { version = "1.33.0", features = ["macros"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio", "sqlite"] }

chia-bls = "0.5.1"
chia-client = "0.5.1"
chia-protocol = "0.5.1"
chia-ssl = "0.2.14"
chia-wallet = "0.5.1"
clvm-traits = "0.5.1"
clvm-utils = "0.5.1"

clvmr = "0.5.0"
sha2 = "0.9.9"
thiserror = "1.0.50"
native-tls = "0.2.11"
hex = "0.4.3"
bech32 = "0.9.1"
rand = "0.8.5"
rand_chacha = "0.3.1"

[dev-dependencies]
bip39 = "2.0.0"
chia = "0.5.2"
hex-literal = "0.4.1"
once_cell = "1.19.0"
